### ISSUE TITLE
Keep images up to date

### ISSUE THREAD

**Issue by JensAc** [gardener-community/etcd#1]
I think it would be worthwhile to investigate whether we could update the specified image versions automatically. E.g. we have an outdated image version [here](https://github.com/gardener-community/etcd/blob/2c202878d7783a2576a52b1b77814e95a8ae788b/charts/etcd/values.yaml#L20). Maybe renovate could do the job?

**Comment by gesslein** [comment]
Just as you wrote this, I already updated the images to a version already in use by a customer, further updates might need more testing

**Comment by mxmxchere** [comment]
renovate is now set up to track images

**Comment by JensAc** [comment]
Nice :raised_hands:
